# Generated by Django 4.2.6 on 2023-10-20 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devEui', models.CharField(max_length=100)),
                ('devName', models.CharField(max_length=100)),
                ('decodedPayload', models.JSONField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ManyToManyField(blank=True, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
