# Generated by Django 4.2.6 on 2023-10-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_alter_devices_deveui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='decodedPayload',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='time',
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decodedPayload', models.JSONField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='collab.devices')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
