# Generated by Django 4.2.6 on 2023-10-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_remove_devices_decodedpayload_remove_devices_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDataVars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=100)),
                ('variable', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='decodedPayload',
        ),
        migrations.AddField(
            model_name='devicedata',
            name='decodedPayload',
            field=models.ManyToManyField(related_name='data', to='collab.devicedatavars'),
        ),
    ]
