# Generated by Django 4.2.6 on 2023-10-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0005_alter_devicedatavars_variable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicedata',
            options={},
        ),
        migrations.AddField(
            model_name='devices',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
