# Generated by Django 4.2.6 on 2023-10-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0006_alter_devicedata_options_devices_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Ignores users and shows the device for everyone'),
        ),
    ]
