# Generated by Django 4.2.6 on 2023-10-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0007_alter_devices_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='decodedPayload',
            field=models.ManyToManyField(related_name='data_vars', to='collab.devicedatavars'),
        ),
    ]
