# Generated by Django 4.2.6 on 2023-10-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0008_alter_devicedata_decodedpayload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicedata',
            options={'verbose_name': 'Device Data', 'verbose_name_plural': 'Device Data'},
        ),
        migrations.AlterModelOptions(
            name='devicedatavars',
            options={'verbose_name': 'Device Data Variable', 'verbose_name_plural': 'Device Data Variables'},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelTable(
            name='devicedata',
            table='device_data',
        ),
        migrations.AlterModelTable(
            name='devicedatavars',
            table='device_data_vars',
        ),
        migrations.AlterModelTable(
            name='devices',
            table='devices',
        ),
    ]
