# Generated by Django 4.2.6 on 2023-10-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0009_alter_devicedata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicedata',
            options={'managed': True, 'verbose_name': 'Device Data', 'verbose_name_plural': 'Device Data'},
        ),
        migrations.AlterModelOptions(
            name='devicedatavars',
            options={'managed': True, 'verbose_name': 'Device Data Variable', 'verbose_name_plural': 'Device Data Variables'},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'managed': True, 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
    ]
