# Generated by Django 4.2.6 on 2023-11-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0010_alter_devicedata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField()),
                ('webhook_name', models.CharField(max_length=250)),
                ('webhook_secret', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'db_table': 'webhooks',
                'managed': True,
            },
        ),
    ]
